# image: https://github.com/users/arimal199/packages/container/package/alpine-webmin
# docs: https://github.com/arimal199/alpine-webmin

version: '3.8'

services:
  webmin:
    image: websoft9dev/webmin:${APP_VERSION}
    container_name: ${APP_NAME}
    environment:
      - WEBMIN_PASSWORD=${APP_PASSWORD}
    ports:
      - '${APP_HTTP_PORT}:10000'

networks:
  default:
    name: ${APP_NETWORK}
    external: true
